//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstornoFP.WSFP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.datasus.org/", ConfigurationName="WSFP.ServicoSolicitacaoWS")]
    public interface ServicoSolicitacaoWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executarSolicitacaoReturn")]
        EstornoFP.WSFP.AutorizacaoDTO executarSolicitacao(EstornoFP.WSFP.SolicitacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executarSolicitacaoReturn")]
        System.Threading.Tasks.Task<EstornoFP.WSFP.AutorizacaoDTO> executarSolicitacaoAsync(EstornoFP.WSFP.SolicitacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarAutorizacaoReturn")]
        EstornoFP.WSFP.ConfirmacaoAutorizacaoDTO confirmarAutorizacao(EstornoFP.WSFP.ConfirmacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarAutorizacaoReturn")]
        System.Threading.Tasks.Task<EstornoFP.WSFP.ConfirmacaoAutorizacaoDTO> confirmarAutorizacaoAsync(EstornoFP.WSFP.ConfirmacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarRecebimentoReturn")]
        EstornoFP.WSFP.ConfirmacaoRecebimentoDTO confirmarRecebimento(EstornoFP.WSFP.RecebimentoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarRecebimentoReturn")]
        System.Threading.Tasks.Task<EstornoFP.WSFP.ConfirmacaoRecebimentoDTO> confirmarRecebimentoAsync(EstornoFP.WSFP.RecebimentoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pesquisarAutorizacoesReturn")]
        EstornoFP.WSFP.RetornoPesquisaDTO pesquisarAutorizacoes(EstornoFP.WSFP.PesquisaDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pesquisarAutorizacoesReturn")]
        System.Threading.Tasks.Task<EstornoFP.WSFP.RetornoPesquisaDTO> pesquisarAutorizacoesAsync(EstornoFP.WSFP.PesquisaDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executarEstornoReturn")]
        EstornoFP.WSFP.ConfirmacaoEstornoDTO executarEstorno(EstornoFP.WSFP.EstornoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executarEstornoReturn")]
        System.Threading.Tasks.Task<EstornoFP.WSFP.ConfirmacaoEstornoDTO> executarEstornoAsync(EstornoFP.WSFP.EstornoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class SolicitacaoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private string dnaEstacaoField;
        
        private System.Nullable<System.DateTime> dtEmissaoReceitaField;
        
        private string dtEmissaoReceitaAsStringField;
        
        private string nuCnpjField;
        
        private string nuCpfField;
        
        private string nuCrmField;
        
        private string sgUfCrmField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia {
            get {
                return this.coSolicitacaoFarmaciaField;
            }
            set {
                this.coSolicitacaoFarmaciaField = value;
                this.RaisePropertyChanged("coSolicitacaoFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dnaEstacao {
            get {
                return this.dnaEstacaoField;
            }
            set {
                this.dnaEstacaoField = value;
                this.RaisePropertyChanged("dnaEstacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtEmissaoReceita {
            get {
                return this.dtEmissaoReceitaField;
            }
            set {
                this.dtEmissaoReceitaField = value;
                this.RaisePropertyChanged("dtEmissaoReceita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dtEmissaoReceitaAsString {
            get {
                return this.dtEmissaoReceitaAsStringField;
            }
            set {
                this.dtEmissaoReceitaAsStringField = value;
                this.RaisePropertyChanged("dtEmissaoReceitaAsString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj {
            get {
                return this.nuCnpjField;
            }
            set {
                this.nuCnpjField = value;
                this.RaisePropertyChanged("nuCnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCpf {
            get {
                return this.nuCpfField;
            }
            set {
                this.nuCpfField = value;
                this.RaisePropertyChanged("nuCpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCrm {
            get {
                return this.nuCrmField;
            }
            set {
                this.nuCrmField = value;
                this.RaisePropertyChanged("nuCrm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sgUfCrm {
            get {
                return this.sgUfCrmField;
            }
            set {
                this.sgUfCrmField = value;
                this.RaisePropertyChanged("sgUfCrm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class MedicamentoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coCodigoBarraField;
        
        private string dsUnidApresentacaoField;
        
        private string inAutorizacaoEstornoField;
        
        private string inAutorizacaoMedicamentoField;
        
        private double qtAutorizadaField;
        
        private double qtDevolvidaField;
        
        private double qtEstornadaField;
        
        private double qtPrescritaField;
        
        private double qtSolicitadaField;
        
        private string statusTransacaoField;
        
        private double vlPrecoSubsidiadoMSField;
        
        private double vlPrecoSubsidiadoPacienteField;
        
        private double vlPrecoSubsidiadoPacientePosEstornoField;
        
        private double vlPrecoVendaField;
        
        private double vlrSubsidiadoMSPosEstornoField;
        
        private double vlrTotalVendaPosEstornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coCodigoBarra {
            get {
                return this.coCodigoBarraField;
            }
            set {
                this.coCodigoBarraField = value;
                this.RaisePropertyChanged("coCodigoBarra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dsUnidApresentacao {
            get {
                return this.dsUnidApresentacaoField;
            }
            set {
                this.dsUnidApresentacaoField = value;
                this.RaisePropertyChanged("dsUnidApresentacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoEstorno {
            get {
                return this.inAutorizacaoEstornoField;
            }
            set {
                this.inAutorizacaoEstornoField = value;
                this.RaisePropertyChanged("inAutorizacaoEstorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoMedicamento {
            get {
                return this.inAutorizacaoMedicamentoField;
            }
            set {
                this.inAutorizacaoMedicamentoField = value;
                this.RaisePropertyChanged("inAutorizacaoMedicamento");
            }
        }
        
        /// <remarks/>
        public double qtAutorizada {
            get {
                return this.qtAutorizadaField;
            }
            set {
                this.qtAutorizadaField = value;
                this.RaisePropertyChanged("qtAutorizada");
            }
        }
        
        /// <remarks/>
        public double qtDevolvida {
            get {
                return this.qtDevolvidaField;
            }
            set {
                this.qtDevolvidaField = value;
                this.RaisePropertyChanged("qtDevolvida");
            }
        }
        
        /// <remarks/>
        public double qtEstornada {
            get {
                return this.qtEstornadaField;
            }
            set {
                this.qtEstornadaField = value;
                this.RaisePropertyChanged("qtEstornada");
            }
        }
        
        /// <remarks/>
        public double qtPrescrita {
            get {
                return this.qtPrescritaField;
            }
            set {
                this.qtPrescritaField = value;
                this.RaisePropertyChanged("qtPrescrita");
            }
        }
        
        /// <remarks/>
        public double qtSolicitada {
            get {
                return this.qtSolicitadaField;
            }
            set {
                this.qtSolicitadaField = value;
                this.RaisePropertyChanged("qtSolicitada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusTransacao {
            get {
                return this.statusTransacaoField;
            }
            set {
                this.statusTransacaoField = value;
                this.RaisePropertyChanged("statusTransacao");
            }
        }
        
        /// <remarks/>
        public double vlPrecoSubsidiadoMS {
            get {
                return this.vlPrecoSubsidiadoMSField;
            }
            set {
                this.vlPrecoSubsidiadoMSField = value;
                this.RaisePropertyChanged("vlPrecoSubsidiadoMS");
            }
        }
        
        /// <remarks/>
        public double vlPrecoSubsidiadoPaciente {
            get {
                return this.vlPrecoSubsidiadoPacienteField;
            }
            set {
                this.vlPrecoSubsidiadoPacienteField = value;
                this.RaisePropertyChanged("vlPrecoSubsidiadoPaciente");
            }
        }
        
        /// <remarks/>
        public double vlPrecoSubsidiadoPacientePosEstorno {
            get {
                return this.vlPrecoSubsidiadoPacientePosEstornoField;
            }
            set {
                this.vlPrecoSubsidiadoPacientePosEstornoField = value;
                this.RaisePropertyChanged("vlPrecoSubsidiadoPacientePosEstorno");
            }
        }
        
        /// <remarks/>
        public double vlPrecoVenda {
            get {
                return this.vlPrecoVendaField;
            }
            set {
                this.vlPrecoVendaField = value;
                this.RaisePropertyChanged("vlPrecoVenda");
            }
        }
        
        /// <remarks/>
        public double vlrSubsidiadoMSPosEstorno {
            get {
                return this.vlrSubsidiadoMSPosEstornoField;
            }
            set {
                this.vlrSubsidiadoMSPosEstornoField = value;
                this.RaisePropertyChanged("vlrSubsidiadoMSPosEstorno");
            }
        }
        
        /// <remarks/>
        public double vlrTotalVendaPosEstorno {
            get {
                return this.vlrTotalVendaPosEstornoField;
            }
            set {
                this.vlrTotalVendaPosEstornoField = value;
                this.RaisePropertyChanged("vlrTotalVendaPosEstorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoEstornoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string descMensagemErroField;
        
        private string inSituacaoEstornoField;
        
        private string nuEstornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagemErro {
            get {
                return this.descMensagemErroField;
            }
            set {
                this.descMensagemErroField = value;
                this.RaisePropertyChanged("descMensagemErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inSituacaoEstorno {
            get {
                return this.inSituacaoEstornoField;
            }
            set {
                this.inSituacaoEstornoField = value;
                this.RaisePropertyChanged("inSituacaoEstorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuEstorno {
            get {
                return this.nuEstornoField;
            }
            set {
                this.nuEstornoField = value;
                this.RaisePropertyChanged("nuEstorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class EstornoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string nuAutorizacaoField;
        
        private string nuCnpjField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj {
            get {
                return this.nuCnpjField;
            }
            set {
                this.nuCnpjField = value;
                this.RaisePropertyChanged("nuCnpj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ItemPesquisaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private System.Nullable<System.DateTime> dtAutorizacaoField;
        
        private System.Nullable<System.DateTime> dtRecebimentoField;
        
        private System.Nullable<System.DateTime> dtSolicitacaoField;
        
        private string nuAutorizacaoField;
        
        private string nuCpfField;
        
        private string nuCrmField;
        
        private string nuCupomFiscalField;
        
        private string sgUfCrmField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia {
            get {
                return this.coSolicitacaoFarmaciaField;
            }
            set {
                this.coSolicitacaoFarmaciaField = value;
                this.RaisePropertyChanged("coSolicitacaoFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtAutorizacao {
            get {
                return this.dtAutorizacaoField;
            }
            set {
                this.dtAutorizacaoField = value;
                this.RaisePropertyChanged("dtAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtRecebimento {
            get {
                return this.dtRecebimentoField;
            }
            set {
                this.dtRecebimentoField = value;
                this.RaisePropertyChanged("dtRecebimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtSolicitacao {
            get {
                return this.dtSolicitacaoField;
            }
            set {
                this.dtSolicitacaoField = value;
                this.RaisePropertyChanged("dtSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCpf {
            get {
                return this.nuCpfField;
            }
            set {
                this.nuCpfField = value;
                this.RaisePropertyChanged("nuCpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCrm {
            get {
                return this.nuCrmField;
            }
            set {
                this.nuCrmField = value;
                this.RaisePropertyChanged("nuCrm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal {
            get {
                return this.nuCupomFiscalField;
            }
            set {
                this.nuCupomFiscalField = value;
                this.RaisePropertyChanged("nuCupomFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sgUfCrm {
            get {
                return this.sgUfCrmField;
            }
            set {
                this.sgUfCrmField = value;
                this.RaisePropertyChanged("sgUfCrm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class RetornoPesquisaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ItemPesquisaDTO[] arrItemPesquisaDTOField;
        
        private string codigoRetornoField;
        
        private System.Nullable<System.DateTime> dataFimField;
        
        private System.Nullable<System.DateTime> dataInicioField;
        
        private string mensagemRetornoField;
        
        private string nuCnpjField;
        
        private string nuCnpjMatrizField;
        
        private int numeroPaginaField;
        
        private int quantidadePaginasField;
        
        private string statusTransacaoField;
        
        private int totalTransacoesField;
        
        private int totalTransacoesPaginaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ItemPesquisaDTO[] arrItemPesquisaDTO {
            get {
                return this.arrItemPesquisaDTOField;
            }
            set {
                this.arrItemPesquisaDTOField = value;
                this.RaisePropertyChanged("arrItemPesquisaDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("codigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFim {
            get {
                return this.dataFimField;
            }
            set {
                this.dataFimField = value;
                this.RaisePropertyChanged("dataFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
                this.RaisePropertyChanged("dataInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
                this.RaisePropertyChanged("mensagemRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj {
            get {
                return this.nuCnpjField;
            }
            set {
                this.nuCnpjField = value;
                this.RaisePropertyChanged("nuCnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpjMatriz {
            get {
                return this.nuCnpjMatrizField;
            }
            set {
                this.nuCnpjMatrizField = value;
                this.RaisePropertyChanged("nuCnpjMatriz");
            }
        }
        
        /// <remarks/>
        public int numeroPagina {
            get {
                return this.numeroPaginaField;
            }
            set {
                this.numeroPaginaField = value;
                this.RaisePropertyChanged("numeroPagina");
            }
        }
        
        /// <remarks/>
        public int quantidadePaginas {
            get {
                return this.quantidadePaginasField;
            }
            set {
                this.quantidadePaginasField = value;
                this.RaisePropertyChanged("quantidadePaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusTransacao {
            get {
                return this.statusTransacaoField;
            }
            set {
                this.statusTransacaoField = value;
                this.RaisePropertyChanged("statusTransacao");
            }
        }
        
        /// <remarks/>
        public int totalTransacoes {
            get {
                return this.totalTransacoesField;
            }
            set {
                this.totalTransacoesField = value;
                this.RaisePropertyChanged("totalTransacoes");
            }
        }
        
        /// <remarks/>
        public int totalTransacoesPagina {
            get {
                return this.totalTransacoesPaginaField;
            }
            set {
                this.totalTransacoesPaginaField = value;
                this.RaisePropertyChanged("totalTransacoesPagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class PesquisaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> dataFimField;
        
        private System.Nullable<System.DateTime> dataInicioField;
        
        private string nuCnpjField;
        
        private string nuCnpjMatrizField;
        
        private int numeroPaginaField;
        
        private string statusTransacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFim {
            get {
                return this.dataFimField;
            }
            set {
                this.dataFimField = value;
                this.RaisePropertyChanged("dataFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
                this.RaisePropertyChanged("dataInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj {
            get {
                return this.nuCnpjField;
            }
            set {
                this.nuCnpjField = value;
                this.RaisePropertyChanged("nuCnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpjMatriz {
            get {
                return this.nuCnpjMatrizField;
            }
            set {
                this.nuCnpjMatrizField = value;
                this.RaisePropertyChanged("nuCnpjMatriz");
            }
        }
        
        /// <remarks/>
        public int numeroPagina {
            get {
                return this.numeroPaginaField;
            }
            set {
                this.numeroPaginaField = value;
                this.RaisePropertyChanged("numeroPagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusTransacao {
            get {
                return this.statusTransacaoField;
            }
            set {
                this.statusTransacaoField = value;
                this.RaisePropertyChanged("statusTransacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoRecebimentoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string codigoRetornoField;
        
        private string cupomVinculadoField;
        
        private string mensagemRetornoField;
        
        private string nuAutorizacaoField;
        
        private string statusRecebimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("codigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cupomVinculado {
            get {
                return this.cupomVinculadoField;
            }
            set {
                this.cupomVinculadoField = value;
                this.RaisePropertyChanged("cupomVinculado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
                this.RaisePropertyChanged("mensagemRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusRecebimento {
            get {
                return this.statusRecebimentoField;
            }
            set {
                this.statusRecebimentoField = value;
                this.RaisePropertyChanged("statusRecebimento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class RecebimentoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string nuAutorizacaoField;
        
        private string nuCupomFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal {
            get {
                return this.nuCupomFiscalField;
            }
            set {
                this.nuCupomFiscalField = value;
                this.RaisePropertyChanged("nuCupomFiscal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoAutorizacaoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private string descMensagemErroField;
        
        private string inAutorizacaoSolicitacaoField;
        
        private string noPessoaField;
        
        private string nuAutorizacaoField;
        
        private string nuCupomFiscalField;
        
        private string statusConfirmacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia {
            get {
                return this.coSolicitacaoFarmaciaField;
            }
            set {
                this.coSolicitacaoFarmaciaField = value;
                this.RaisePropertyChanged("coSolicitacaoFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagemErro {
            get {
                return this.descMensagemErroField;
            }
            set {
                this.descMensagemErroField = value;
                this.RaisePropertyChanged("descMensagemErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoSolicitacao {
            get {
                return this.inAutorizacaoSolicitacaoField;
            }
            set {
                this.inAutorizacaoSolicitacaoField = value;
                this.RaisePropertyChanged("inAutorizacaoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string noPessoa {
            get {
                return this.noPessoaField;
            }
            set {
                this.noPessoaField = value;
                this.RaisePropertyChanged("noPessoa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal {
            get {
                return this.nuCupomFiscalField;
            }
            set {
                this.nuCupomFiscalField = value;
                this.RaisePropertyChanged("nuCupomFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusConfirmacao {
            get {
                return this.statusConfirmacaoField;
            }
            set {
                this.statusConfirmacaoField = value;
                this.RaisePropertyChanged("statusConfirmacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coSolicitacaoFarmaciaField;
        
        private string descMensagemField;
        
        private string nuAutorizacaoField;
        
        private string nuCupomFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia {
            get {
                return this.coSolicitacaoFarmaciaField;
            }
            set {
                this.coSolicitacaoFarmaciaField = value;
                this.RaisePropertyChanged("coSolicitacaoFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagem {
            get {
                return this.descMensagemField;
            }
            set {
                this.descMensagemField = value;
                this.RaisePropertyChanged("descMensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal {
            get {
                return this.nuCupomFiscalField;
            }
            set {
                this.nuCupomFiscalField = value;
                this.RaisePropertyChanged("nuCupomFiscal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class AutorizacaoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private string descMensagemErroField;
        
        private string inAutorizacaoSolicitacaoField;
        
        private string noPessoaField;
        
        private string nuAutorizacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO {
            get {
                return this.arrMedicamentoDTOField;
            }
            set {
                this.arrMedicamentoDTOField = value;
                this.RaisePropertyChanged("arrMedicamentoDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia {
            get {
                return this.coSolicitacaoFarmaciaField;
            }
            set {
                this.coSolicitacaoFarmaciaField = value;
                this.RaisePropertyChanged("coSolicitacaoFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagemErro {
            get {
                return this.descMensagemErroField;
            }
            set {
                this.descMensagemErroField = value;
                this.RaisePropertyChanged("descMensagemErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoSolicitacao {
            get {
                return this.inAutorizacaoSolicitacaoField;
            }
            set {
                this.inAutorizacaoSolicitacaoField = value;
                this.RaisePropertyChanged("inAutorizacaoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string noPessoa {
            get {
                return this.noPessoaField;
            }
            set {
                this.noPessoaField = value;
                this.RaisePropertyChanged("noPessoa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao {
            get {
                return this.nuAutorizacaoField;
            }
            set {
                this.nuAutorizacaoField = value;
                this.RaisePropertyChanged("nuAutorizacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(UsuarioFarmaciaDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class UsuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senhaFarmaciaField;
        
        private string senhaVendedorField;
        
        private string usuarioFarmaciaField;
        
        private string usuarioVendedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string senhaFarmacia {
            get {
                return this.senhaFarmaciaField;
            }
            set {
                this.senhaFarmaciaField = value;
                this.RaisePropertyChanged("senhaFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string senhaVendedor {
            get {
                return this.senhaVendedorField;
            }
            set {
                this.senhaVendedorField = value;
                this.RaisePropertyChanged("senhaVendedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string usuarioFarmacia {
            get {
                return this.usuarioFarmaciaField;
            }
            set {
                this.usuarioFarmaciaField = value;
                this.RaisePropertyChanged("usuarioFarmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string usuarioVendedor {
            get {
                return this.usuarioVendedorField;
            }
            set {
                this.usuarioVendedorField = value;
                this.RaisePropertyChanged("usuarioVendedor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class UsuarioFarmaciaDTO : UsuarioDTO {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoSolicitacaoWSChannel : EstornoFP.WSFP.ServicoSolicitacaoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoSolicitacaoWSClient : System.ServiceModel.ClientBase<EstornoFP.WSFP.ServicoSolicitacaoWS>, EstornoFP.WSFP.ServicoSolicitacaoWS {
        
        public ServicoSolicitacaoWSClient() {
        }
        
        public ServicoSolicitacaoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoSolicitacaoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSolicitacaoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSolicitacaoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EstornoFP.WSFP.AutorizacaoDTO executarSolicitacao(EstornoFP.WSFP.SolicitacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.executarSolicitacao(in0, in1);
        }
        
        public System.Threading.Tasks.Task<EstornoFP.WSFP.AutorizacaoDTO> executarSolicitacaoAsync(EstornoFP.WSFP.SolicitacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.executarSolicitacaoAsync(in0, in1);
        }
        
        public EstornoFP.WSFP.ConfirmacaoAutorizacaoDTO confirmarAutorizacao(EstornoFP.WSFP.ConfirmacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.confirmarAutorizacao(in0, in1);
        }
        
        public System.Threading.Tasks.Task<EstornoFP.WSFP.ConfirmacaoAutorizacaoDTO> confirmarAutorizacaoAsync(EstornoFP.WSFP.ConfirmacaoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.confirmarAutorizacaoAsync(in0, in1);
        }
        
        public EstornoFP.WSFP.ConfirmacaoRecebimentoDTO confirmarRecebimento(EstornoFP.WSFP.RecebimentoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.confirmarRecebimento(in0, in1);
        }
        
        public System.Threading.Tasks.Task<EstornoFP.WSFP.ConfirmacaoRecebimentoDTO> confirmarRecebimentoAsync(EstornoFP.WSFP.RecebimentoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.confirmarRecebimentoAsync(in0, in1);
        }
        
        public EstornoFP.WSFP.RetornoPesquisaDTO pesquisarAutorizacoes(EstornoFP.WSFP.PesquisaDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.pesquisarAutorizacoes(in0, in1);
        }
        
        public System.Threading.Tasks.Task<EstornoFP.WSFP.RetornoPesquisaDTO> pesquisarAutorizacoesAsync(EstornoFP.WSFP.PesquisaDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.pesquisarAutorizacoesAsync(in0, in1);
        }
        
        public EstornoFP.WSFP.ConfirmacaoEstornoDTO executarEstorno(EstornoFP.WSFP.EstornoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.executarEstorno(in0, in1);
        }
        
        public System.Threading.Tasks.Task<EstornoFP.WSFP.ConfirmacaoEstornoDTO> executarEstornoAsync(EstornoFP.WSFP.EstornoDTO in0, EstornoFP.WSFP.UsuarioFarmaciaDTO in1) {
            return base.Channel.executarEstornoAsync(in0, in1);
        }
    }
}
